import { NextResponse } from "next/server"
import { supabase } from "@/lib/supabase"
import { cookies } from "next/headers"
import { createHash } from "crypto"
import { notify } from "@/lib/notify"

function buildAgreementText(seed: any, nodes: any[], date: string): string {
  const nodeLines = nodes.map(n =>
    `  ${n.role} — ${n.slice}% equity${n.milestone ? `\n  Milestone: ${n.milestone}` : ""}`
  ).join("\n\n")

  return `SEED AGREEMENT
==============
${seed.title}

Generated by Broke Founders on ${date}

PROBLEM
${seed.problem}

PARTIES
Originator: @${seed.users?.username} — ${seed.originator_stake}% equity

NODES
${nodeLines}
${seed.graduation_threshold ? `\nGRADUATION THRESHOLD\n${seed.graduation_threshold}\n` : ""}
TERMS
By signing this agreement, each party confirms their role, equity allocation,
and milestone commitment as stated above. Equity vests upon graduation of the
seed as defined by the graduation threshold.`
}

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params
  const cookieStore = await cookies()
  const raw = cookieStore.get("bf_user")?.value
  const session = raw ? JSON.parse(raw) : null

  const { data: seed } = await supabase
    .from("seeds")
    .select("id, title, problem, originator_stake, graduation_threshold, originator_id, users(username)")
    .eq("slug", slug)
    .single()

  if (!seed) return NextResponse.json({ error: "Not found" }, { status: 404 })

  const { data: nodes } = await supabase
    .from("nodes")
    .select("role, slice, milestone, status, contributor_id")
    .eq("seed_id", seed.id)

  const allActive = nodes?.length && nodes.every(n => n.status === "active")
  if (!allActive) return NextResponse.json({ available: false })

  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })
  const text = buildAgreementText(seed, nodes!, date)
  const contentHash = createHash("sha256").update(text).digest("hex")

  const { data: signers } = await supabase
    .from("agreements")
    .select("user_id, signed_at")
    .eq("seed_id", seed.id)

  const currentUserSigned = session ? (signers ?? []).some(s => s.user_id === session.id) : false
  const isContributor = session
    ? (nodes ?? []).some(n => n.contributor_id === session.id) || seed.originator_id === session.id
    : false

  return NextResponse.json({
    available: true,
    text,
    contentHash,
    signers: signers ?? [],
    currentUserSigned,
    isContributor,
  })
}

export async function POST(
  req: Request,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params
  const cookieStore = await cookies()
  const raw = cookieStore.get("bf_user")?.value
  if (!raw) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  const session = JSON.parse(raw)

  const { content_hash } = await req.json()

  const { data: seed } = await supabase
    .from("seeds")
    .select("id, title, problem, originator_stake, graduation_threshold, originator_id, users(username)")
    .eq("slug", slug)
    .single()

  if (!seed) return NextResponse.json({ error: "Not found" }, { status: 404 })

  const { data: nodes } = await supabase
    .from("nodes")
    .select("role, slice, milestone, status, contributor_id")
    .eq("seed_id", seed.id)

  const allActive = nodes?.length && nodes.every(n => n.status === "active")
  if (!allActive) return NextResponse.json({ error: "Not all nodes are active" }, { status: 403 })

  const isContributor = (nodes ?? []).some(n => n.contributor_id === session.id) || seed.originator_id === session.id
  if (!isContributor) return NextResponse.json({ error: "Not a contributor" }, { status: 403 })

  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })
  const text = buildAgreementText(seed, nodes!, date)
  const expected = createHash("sha256").update(text).digest("hex")
  if (content_hash !== expected) return NextResponse.json({ error: "Content hash mismatch" }, { status: 400 })

  const { error } = await supabase
    .from("agreements")
    .insert({ seed_id: seed.id, user_id: session.id, content_hash })

  if (error?.code === "23505") return NextResponse.json({ error: "Already signed" }, { status: 409 })
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  await notify({
    user_id: seed.originator_id,
    type: "seed_graduated",
    title: `${seed.title} agreement signed`,
    body: `@${session.github_username} signed the seed agreement`,
    link: `/seeds/${slug}`,
  })

  return NextResponse.json({ success: true })
}
