const GH = "https://api.github.com"

function parseRepo(repoUrl: string): string {
  return repoUrl
    .replace(/^https?:\/\/github\.com\//, "")
    .replace(/^github\.com\//, "")
    .replace(/\/$/, "")
}

function ghHeaders(token: string): HeadersInit {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "Content-Type": "application/json",
  }
}

export async function inviteCollaborator(repoUrl: string, username: string, token: string): Promise<void> {
  const repo = parseRepo(repoUrl)
  const res = await fetch(`${GH}/repos/${repo}/collaborators/${username}`, {
    method: "PUT",
    headers: ghHeaders(token),
    body: JSON.stringify({ permission: "push" }),
  })
  if (!res.ok && res.status !== 201 && res.status !== 204) {
    const body = await res.text()
    throw new Error(`inviteCollaborator failed (${res.status}): ${body}`)
  }
}

export async function createBranch(repoUrl: string, branchName: string, token: string): Promise<void> {
  const repo = parseRepo(repoUrl)

  // Get default branch info
  const repoRes = await fetch(`${GH}/repos/${repo}`, { headers: ghHeaders(token) })
  if (!repoRes.ok) throw new Error(`Failed to fetch repo info (${repoRes.status})`)
  const repoData = await repoRes.json()
  const defaultBranch = repoData.default_branch || "main"

  // Get SHA of default branch HEAD
  const refRes = await fetch(`${GH}/repos/${repo}/git/ref/heads/${defaultBranch}`, {
    headers: ghHeaders(token),
  })
  if (!refRes.ok) throw new Error(`Failed to fetch ref (${refRes.status})`)
  const refData = await refRes.json()
  const sha = refData.object.sha

  // Create the new branch
  const createRes = await fetch(`${GH}/repos/${repo}/git/refs`, {
    method: "POST",
    headers: ghHeaders(token),
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha }),
  })

  // 422 = branch already exists — treat as success
  if (!createRes.ok && createRes.status !== 422) {
    const body = await createRes.text()
    throw new Error(`createBranch failed (${createRes.status}): ${body}`)
  }
}

export async function pushFile(
  repoUrl: string,
  path: string,
  content: string,
  message: string,
  token: string
): Promise<void> {
  const repo = parseRepo(repoUrl)
  const encoded = Buffer.from(content, "utf-8").toString("base64")

  // Check if file already exists (need its SHA to update)
  let existingSha: string | undefined
  const getRes = await fetch(`${GH}/repos/${repo}/contents/${path}`, {
    headers: ghHeaders(token),
  })
  if (getRes.ok) {
    const existing = await getRes.json()
    existingSha = existing.sha
  }

  const body: Record<string, string> = { message, content: encoded }
  if (existingSha) body.sha = existingSha

  const putRes = await fetch(`${GH}/repos/${repo}/contents/${path}`, {
    method: "PUT",
    headers: ghHeaders(token),
    body: JSON.stringify(body),
  })
  if (!putRes.ok) {
    const err = await putRes.text()
    throw new Error(`pushFile failed (${putRes.status}): ${err}`)
  }
}

const ROLE_FOLDERS: [string[], string[]][] = [
  [["frontend"], ["/src/components", "/src/pages", "/src/styles"]],
  [["backend"], ["/src/api", "/src/lib", "/src/middleware"]],
  [["full stack", "fullstack"], ["/src"]],
  [["ui", "ux", "designer", "design"], ["/design", "/src/styles"]],
  [["devops", "infra", "infrastructure", "sre"], ["/infrastructure", "/scripts", "/.github"]],
  [["growth", "marketer", "marketing"], ["/marketing", "/public"]],
  [["copywriter", "copy", "writer"], ["/content", "/public"]],
  [["seo"], ["/content", "/public/seo"]],
]

function foldersForRole(role: string): string[] {
  const lower = role.toLowerCase()
  for (const [keywords, folders] of ROLE_FOLDERS) {
    if (keywords.some(k => lower.includes(k))) return folders
  }
  const slug = lower.replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "")
  return [`/src/${slug}`]
}

export function generateCodebaseMap(nodes: { role: string }[]): string {
  const lines = ["# Codebase Map", "", "Each role owns specific areas of the codebase.", ""]
  lines.push("| Role | Owned Folders |")
  lines.push("|------|---------------|")
  for (const node of nodes) {
    const folders = foldersForRole(node.role)
    lines.push(`| ${node.role} | ${folders.join(", ")} |`)
  }
  lines.push("")
  lines.push("_Generated by Broke Founders_")
  return lines.join("\n")
}

export function generateContributing(
  seedTitle: string,
  nodes: { role: string; slice: number; milestone?: string }[]
): string {
  const branchRows = nodes
    .map(n => {
      const branch = `role/${n.role.toLowerCase().replace(/\s+/g, "-")}`
      const folders = foldersForRole(n.role).join(", ")
      const milestone = n.milestone || "—"
      return `| ${n.role} | \`${branch}\` | ${folders} | ${milestone} |`
    })
    .join("\n")

  return `# Contributing to ${seedTitle}

## Branch convention
Each role works on their own branch. Never push directly to main.

| Role | Branch | Ownership | Milestone |
|------|--------|-----------|-----------|
${branchRows}

## Process
1. Pull latest from main
2. Work on your branch only
3. Open a PR when your milestone is complete
4. Originator reviews and merges

## Questions?
Use the seed chat on Broke Founders to coordinate with the team.
`
}
